import type { Metadata } from "next";
import Image from 'next/image'



export const metadata: Metadata = {
  title: "ورود / ثبت نام",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="h-screen grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3">
      <div className="flex flex-col justify-center items-center md:col-span-2 lg:col-span-2">
        {children}
      </div>
      <div className="hidden md:flex flex-col justify-center items-center bg-slate-200">
      <Image
        src="/images/background/lock.webp"
        priority={false}
        width={400}
        height={478}
        alt="login page vector"
        />
      </div>
    </div>
  );
}
