
// import React from "react";
// import localFont from 'next/font/local';
// import type { Metadata } from "next";
// import axios from "axios";
// import { setupInterceptorsTo } from "@/config/configAxios";
// import dynamic from "next/dynamic";
// import "./globals.css";
// import { ThemeProvider } from "@/components/providers";
// import Header from "@/components/Global/Header";
// import FooterCustom from "@/components/Global/FooterCustom";

// setupInterceptorsTo(axios);





// export const metadata: Metadata = {
//     title: "Niloofar Mousavi Portfolio",
//     description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//     return (
//         <html>
//             <body>
//             <Header></Header>
           
//                     <ThemeProvider>
                        
//                     <main>
                        
//                         {children}
                        
                        
//                         </main>

//                     </ThemeProvider>
//                     <FooterCustom></FooterCustom>
               
//             </body>
          
//         </html>
//     );
// }
import React from "react";
import localFont from 'next/font/local';
import type { Metadata } from "next";
import axios from "axios";
import { setupInterceptorsTo } from "@/config/configAxios";
import dynamic from "next/dynamic";
import "./globals.css";
import { ThemeProvider } from "@/components/providers";
import Header from "@/components/Global/Header";
import FooterCustom from "@/components/Global/FooterCustom";

// Dynamically import ParticleBackground with SSR disabled
const ParticleBackground = dynamic(() => import("@/components/BackGroundAnimation"), {
  ssr: false,
});

setupInterceptorsTo(axios);

export const metadata: Metadata = {
  title: "Niloofar Mousavi Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div className="relative min-h-screen  bg-zinc-900">
          {/* Particle background positioned absolutely */}
          <ParticleBackground />
          
          {/* Your existing content with relative z-index */}
          <div className="relative z-10">
            <Header></Header>
            <ThemeProvider>
              <main>
                {children}
              </main>
            </ThemeProvider>
            <FooterCustom></FooterCustom>
          </div>
        </div>
      </body>
    </html>
  );
}
